### ISSUE TITLE
Plugins cannot access classes that are in main project (Project that loads the plugins)

### ISSUE THREAD

**Issue by DRSchlaubi** [ForYaSee/Plugins#8]
```
at de.foryasee.plugins.loader.impl.PluginLoader.getClassesFromJar(PluginLoader.java:64)
    at de.foryasee.plugins.loader.impl.PluginLoader.lambda$load$0(PluginLoader.java:35)
```

**Comment by DRSchlaubi** [comment]
Class actually wasn't loaded
